
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import Sidebar from "@/Components/Sidebar/Sidebar";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Jesha Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
<div className=" lg:w-full lg:mb-3 ">
  <Header/>
  <Toaster/>
</div>
<div className="grid lg:grid-cols-1 gap-0 md:grid-cols-2 grid-cols-1">
  <div className="lg:block md:block hidden lg:mt-16 "><Sidebar/></div>
  <div className="lg:ml-72 lg:mt-0 md:mt-8 mt-28">{children}</div>
</div>
<div className="lg:ml-72 ">
 <Footer/>
</div>



      </body>
    </html>
  );
}
